<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414074226 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pictures (pct_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pct_filename VARCHAR(255) NOT NULL, pct_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pct_taken_by INT NOT NULL, PRIMARY KEY (pct_id))');
        $this->addSql('CREATE INDEX IDX_8F7C2FC030D1EA78 ON pictures (pct_taken_by)');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT FK_8F7C2FC030D1EA78 FOREIGN KEY (pct_taken_by) REFERENCES "users" (usr_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT FK_8F7C2FC030D1EA78');
        $this->addSql('DROP TABLE pictures');
    }
}
