<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327121238 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pokemons (pkm_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pkm_name VARCHAR(160) NOT NULL, pkm_number INT DEFAULT NULL, PRIMARY KEY (pkm_id))');
        $this->addSql('DROP TABLE pokemon');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pokemon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, number INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE pokemons');
    }
}
