<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407084612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "users" (usr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usr_email VARCHAR(180) NOT NULL, usr_roles JSON NOT NULL, usr_password VARCHAR(255) NOT NULL, usr_lastname VARCHAR(160) NOT NULL, usr_firstname VARCHAR(160) NOT NULL, usr_birthdate DATE NOT NULL, usr_registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (usr_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (usr_email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "users"');
    }
}
