<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407122909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reset_password_requests (rpr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rpr_usr_id INT NOT NULL, PRIMARY KEY (rpr_id))');
        $this->addSql('CREATE INDEX IDX_16646B4167D683ED ON reset_password_requests (rpr_usr_id)');
        $this->addSql('ALTER TABLE reset_password_requests ADD CONSTRAINT FK_16646B4167D683ED FOREIGN KEY (rpr_usr_id) REFERENCES "users" (usr_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reset_password_requests DROP CONSTRAINT FK_16646B4167D683ED');
        $this->addSql('DROP TABLE reset_password_requests');
    }
}
